name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: thompsonja/bazel-buildifier@v0.2.1
        with:
          warnings: all
      - uses: Jerome1337/golint-action@v1.0.2
